/* This file was generated by syncqt. */
#ifndef QT_QTQMLDOM_VERSION_H
#define QT_QTQMLDOM_VERSION_H

#define QTQMLDOM_VERSION_STR "6.10.2"

#define QTQMLDOM_VERSION 0x0601002

#endif // QT_QTQMLDOM_VERSION_H
