/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "6.10.2"

#define QTUITOOLS_VERSION 0x0601002

#endif // QT_QTUITOOLS_VERSION_H
