// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: NoxUDP.proto
// Protobuf C++ Version: 6.31.1

#include "NoxUDP.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace NoxProto {

inline constexpr NoxUDPPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::uint64_t{0u}},
        session_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR NoxUDPPacket::NoxUDPPacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(NoxUDPPacket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NoxUDPPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NoxUDPPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NoxUDPPacketDefaultTypeInternal() {}
  union {
    NoxUDPPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NoxUDPPacketDefaultTypeInternal _NoxUDPPacket_default_instance_;
}  // namespace NoxProto
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_NoxUDP_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_NoxUDP_2eproto = nullptr;
const ::uint32_t
    TableStruct_NoxUDP_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::NoxProto::NoxUDPPacket, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::NoxProto::NoxUDPPacket, _impl_.session_),
        PROTOBUF_FIELD_OFFSET(::NoxProto::NoxUDPPacket, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::NoxProto::NoxUDPPacket, _impl_.timestamp_),
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::NoxProto::NoxUDPPacket)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::NoxProto::_NoxUDPPacket_default_instance_._instance,
};
const char descriptor_table_protodef_NoxUDP_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014NoxUDP.proto\022\010NoxProto\"C\n\014NoxUDPPacket"
    "\022\017\n\007session\030\001 \002(\r\022\017\n\007payload\030\002 \002(\014\022\021\n\tti"
    "mestamp\030\003 \001(\004"
};
static ::absl::once_flag descriptor_table_NoxUDP_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_NoxUDP_2eproto = {
    false,
    false,
    93,
    descriptor_table_protodef_NoxUDP_2eproto,
    "NoxUDP.proto",
    &descriptor_table_NoxUDP_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_NoxUDP_2eproto::offsets,
    file_level_enum_descriptors_NoxUDP_2eproto,
    file_level_service_descriptors_NoxUDP_2eproto,
};
namespace NoxProto {
// ===================================================================

class NoxUDPPacket::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<NoxUDPPacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000005) ^ 0x00000005) != 0;
  }
};

NoxUDPPacket::NoxUDPPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NoxUDPPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NoxProto.NoxUDPPacket)
}
PROTOBUF_NDEBUG_INLINE NoxUDPPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::NoxProto::NoxUDPPacket& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        payload_(arena, from.payload_) {}

NoxUDPPacket::NoxUDPPacket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const NoxUDPPacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, NoxUDPPacket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NoxUDPPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, session_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::session_));

  // @@protoc_insertion_point(copy_constructor:NoxProto.NoxUDPPacket)
}
PROTOBUF_NDEBUG_INLINE NoxUDPPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        payload_(arena) {}

inline void NoxUDPPacket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, session_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::session_));
}
NoxUDPPacket::~NoxUDPPacket() {
  // @@protoc_insertion_point(destructor:NoxProto.NoxUDPPacket)
  SharedDtor(*this);
}
inline void NoxUDPPacket::SharedDtor(MessageLite& self) {
  NoxUDPPacket& this_ = static_cast<NoxUDPPacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL NoxUDPPacket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) NoxUDPPacket(arena);
}
constexpr auto NoxUDPPacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NoxUDPPacket),
                                            alignof(NoxUDPPacket));
}
constexpr auto NoxUDPPacket::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_NoxUDPPacket_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          NoxUDPPacket::IsInitializedImpl,
          &NoxUDPPacket::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<NoxUDPPacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &NoxUDPPacket::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<NoxUDPPacket>(), &NoxUDPPacket::ByteSizeLong,
              &NoxUDPPacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_._cached_size_),
          false,
      },
      &NoxUDPPacket::kDescriptorMethods,
      &descriptor_table_NoxUDP_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull NoxUDPPacket_class_data_ =
        NoxUDPPacket::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
NoxUDPPacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&NoxUDPPacket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(NoxUDPPacket_class_data_.tc_table);
  return NoxUDPPacket_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
NoxUDPPacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    NoxUDPPacket_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NoxProto::NoxUDPPacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required uint32 session = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NoxUDPPacket, _impl_.session_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.session_)}},
    // required bytes payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.payload_)}},
    // optional uint64 timestamp = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(NoxUDPPacket, _impl_.timestamp_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.timestamp_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required uint32 session = 1;
    {PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.session_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // required bytes payload = 2;
    {PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint64 timestamp = 3;
    {PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void NoxUDPPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:NoxProto.NoxUDPPacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.payload_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006u) != 0) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.session_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.session_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL NoxUDPPacket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const NoxUDPPacket& this_ = static_cast<const NoxUDPPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL NoxUDPPacket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const NoxUDPPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:NoxProto.NoxUDPPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required uint32 session = 1;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_session(), target);
  }

  // required bytes payload = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_payload();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // optional uint64 timestamp = 3;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this_._internal_timestamp(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NoxProto.NoxUDPPacket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t NoxUDPPacket::ByteSizeLong(const MessageLite& base) {
  const NoxUDPPacket& this_ = static_cast<const NoxUDPPacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t NoxUDPPacket::ByteSizeLong() const {
  const NoxUDPPacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:NoxProto.NoxUDPPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // required bytes payload = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_payload());
    }
  }
   {
    // optional uint64 timestamp = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_timestamp());
    }
  }
   {
    // required uint32 session = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_session());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void NoxUDPPacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NoxUDPPacket*>(&to_msg);
  auto& from = static_cast<const NoxUDPPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NoxProto.NoxUDPPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_payload(from._internal_payload());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.timestamp_ = from._impl_.timestamp_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.session_ = from._impl_.session_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NoxUDPPacket::CopyFrom(const NoxUDPPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NoxProto.NoxUDPPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool NoxUDPPacket::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const NoxUDPPacket&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void NoxUDPPacket::InternalSwap(NoxUDPPacket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.session_)
      + sizeof(NoxUDPPacket::_impl_.session_)
      - PROTOBUF_FIELD_OFFSET(NoxUDPPacket, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata NoxUDPPacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace NoxProto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_NoxUDP_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
